<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="1136" started-at="2016-06-30T20:42:02Z" finished-at="2016-06-30T20:42:03Z">
    <groups>
      <group name="semaphore">
        <method signature="SemaphoreImplTest.testAcquireThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testAcquireThrowsException" class="com.vasylchenko.java.sources.SemaphoreImplTest"/>
        <method signature="SemaphoreImplTest.testGetAvailablePermitsForMultiThread()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testGetAvailablePermitsForMultiThread" class="com.vasylchenko.java.sources.SemaphoreImplTest"/>
        <method signature="SemaphoreImplTest.testGetAvailablePermitsForSingleThread()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testGetAvailablePermitsForSingleThread" class="com.vasylchenko.java.sources.SemaphoreImplTest"/>
        <method signature="SemaphoreImplTest.testReleaseThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testReleaseThrowsException" class="com.vasylchenko.java.sources.SemaphoreImplTest"/>
      </group> <!-- semaphore -->
      <group name="CyclicBarrier">
        <method signature="SquareSumTest.testGetSquareSum()[pri:0, instance:com.vasylchenko.java.sources.SquareSumTest@d7b1517]" name="testGetSquareSum" class="com.vasylchenko.java.sources.SquareSumTest"/>
        <method signature="SquareSumTest.testReleaseThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SquareSumTest@d7b1517]" name="testReleaseThrowsException" class="com.vasylchenko.java.sources.SquareSumTest"/>
      </group> <!-- CyclicBarrier -->
    </groups>
    <test name="Command line test" duration-ms="1136" started-at="2016-06-30T20:42:02Z" finished-at="2016-06-30T20:42:03Z">
      <class name="com.vasylchenko.java.sources.SquareSumTest">
        <test-method status="PASS" signature="testGetSquareSum()[pri:0, instance:com.vasylchenko.java.sources.SquareSumTest@d7b1517]" name="testGetSquareSum" duration-ms="1104" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSquareSum -->
        <test-method status="PASS" signature="testReleaseThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SquareSumTest@d7b1517]" name="testReleaseThrowsException" duration-ms="0" started-at="2016-06-30T23:42:03Z" finished-at="2016-06-30T23:42:03Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[[Error:] Number of Threads must be more than 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: [Error:] Number of Threads must be more than 0
	at com.vasylchenko.java.sources.SquareSum.getSquareSum(SquareSum.java:12)
	at com.vasylchenko.java.sources.SquareSumTest.testReleaseThrowsException(SquareSumTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReleaseThrowsException -->
      </class> <!-- com.vasylchenko.java.sources.SquareSumTest -->
      <class name="com.vasylchenko.java.sources.SemaphoreImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="setUp" is-config="true" duration-ms="6" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAcquireThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testAcquireThrowsException" duration-ms="1" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <exception class="java.lang.IllegalArgumentException">
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException
	at com.vasylchenko.java.sources.SemaphoreImpl.acquire(SemaphoreImpl.java:47)
	at com.vasylchenko.java.sources.SemaphoreImplTest.testAcquireThrowsException(SemaphoreImplTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAcquireThrowsException -->
        <test-method status="PASS" signature="testGetAvailablePermitsForMultiThread()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testGetAvailablePermitsForMultiThread" duration-ms="2" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAvailablePermitsForMultiThread -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="setUp" is-config="true" duration-ms="0" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetAvailablePermitsForSingleThread()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testGetAvailablePermitsForSingleThread" duration-ms="1" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAvailablePermitsForSingleThread -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="setUp" is-config="true" duration-ms="0" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testReleaseThrowsException()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="testReleaseThrowsException" duration-ms="1" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <exception class="java.lang.IllegalArgumentException">
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException
	at com.vasylchenko.java.sources.SemaphoreImpl.release(SemaphoreImpl.java:77)
	at com.vasylchenko.java.sources.SemaphoreImplTest.testReleaseThrowsException(SemaphoreImplTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReleaseThrowsException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.vasylchenko.java.sources.SemaphoreImplTest@2a18f23c]" name="setUp" is-config="true" duration-ms="0" started-at="2016-06-30T23:42:02Z" finished-at="2016-06-30T23:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.vasylchenko.java.sources.SemaphoreImplTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
